"""
Database models for GetLos_T
"""
from sqlalchemy import Column, Integer, String, DateTime, UniqueConstraint
from sqlalchemy.sql import func
from sqlalchemy.types import JSON
from db import Base


def norm_key(nums: list[int]) -> str:
    """
    Create normalized key from numbers (sorted, zero-padded)
    Example: [5, 12, 23, 34, 45, 49] -> "05-12-23-34-45-49"
    """
    sorted_nums = sorted(nums)
    return "-".join(f"{n:02d}" for n in sorted_nums)


class HistoricalDraw(Base):
    """
    Historical lottery draws
    Stores 6 numbers (1-49) from past lottery results
    """
    __tablename__ = "historical_draws"
    
    id = Column(Integer, primary_key=True, index=True)
    numbers = Column(JSON, nullable=False)  # 6 numbers as JSON array
    key = Column(String, unique=True, index=True, nullable=False)  # normalized key for uniqueness
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    source = Column(String, nullable=True)  # source of data (e.g., "manual_upload", "api", "csv", or draw date YYYY-MM-DD)
    draw_system_id = Column(Integer, nullable=True, index=True)  # Lotto.pl API draw system ID (e.g., 7299)
    sequential_id = Column(Integer, nullable=True, index=True)  # Sequential number starting from 1 for oldest draw (1957-01-27)
    
    def __repr__(self):
        return f"<HistoricalDraw(id={self.id}, numbers={self.numbers}, draw_id={self.draw_system_id})>"


class Pick(Base):
    """
    User generated picks/predictions
    Stores predictions generated by the system
    """
    __tablename__ = "picks"
    
    id = Column(Integer, primary_key=True, index=True)
    numbers = Column(JSON, nullable=False)  # 6 numbers as JSON array
    key = Column(String, unique=True, index=True, nullable=False)  # normalized key for uniqueness
    strategy = Column(String, nullable=False)  # strategy used: random, hot, cold, balanced, combo_based
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        UniqueConstraint("key", name="uq_pick_key"),
    )
    
    def __repr__(self):
        return f"<Pick(id={self.id}, numbers={self.numbers}, strategy={self.strategy})>"


class DrawSchedule(Base):
    """
    Draw schedule periods - defines which days of week draws occurred in different time periods
    Example: 2007-2017 draws were on Wednesday, Friday, Sunday
             2017-now draws are on Tuesday, Thursday, Saturday
    """
    __tablename__ = "draw_schedules"
    
    id = Column(Integer, primary_key=True, index=True)
    date_from = Column(String, nullable=False)  # Start date YYYY-MM-DD
    date_to = Column(String, nullable=True)  # End date YYYY-MM-DD (null = ongoing)
    weekdays = Column(JSON, nullable=False)  # List of weekday numbers: 0=Monday, 1=Tuesday, ..., 6=Sunday
    description = Column(String, nullable=True)  # Optional description like "Modern era", "Historical period"
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    def __repr__(self):
        return f"<DrawSchedule(id={self.id}, from={self.date_from}, to={self.date_to}, days={self.weekdays})>"
