"""
Database models for GetLos_T
"""
from sqlalchemy import Column, Integer, String, DateTime, UniqueConstraint
from sqlalchemy.sql import func
from sqlalchemy.types import JSON
from db import Base


def norm_key(nums: list[int]) -> str:
    """
    Create normalized key from numbers (sorted, zero-padded)
    Example: [5, 12, 23, 34, 45, 52] -> "05-12-23-34-45-52"
    """
    sorted_nums = sorted(nums)
    return "-".join(f"{n:02d}" for n in sorted_nums)


class HistoricalDraw(Base):
    """
    Historical lottery draws
    Stores 6 numbers (1-52) from past lottery results
    """
    __tablename__ = "historical_draws"
    
    id = Column(Integer, primary_key=True, index=True)
    numbers = Column(JSON, nullable=False)  # 6 numbers as JSON array
    key = Column(String, unique=True, index=True, nullable=False)  # normalized key for uniqueness
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    source = Column(String, nullable=True)  # source of data (e.g., "manual_upload", "api", "csv")
    
    def __repr__(self):
        return f"<HistoricalDraw(id={self.id}, numbers={self.numbers})>"


class Pick(Base):
    """
    User generated picks/predictions
    Stores predictions generated by the system
    """
    __tablename__ = "picks"
    
    id = Column(Integer, primary_key=True, index=True)
    numbers = Column(JSON, nullable=False)  # 6 numbers as JSON array
    key = Column(String, unique=True, index=True, nullable=False)  # normalized key for uniqueness
    strategy = Column(String, nullable=False)  # strategy used: random, hot, cold, balanced, combo_based
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    __table_args__ = (
        UniqueConstraint("key", name="uq_pick_key"),
    )
    
    def __repr__(self):
        return f"<Pick(id={self.id}, numbers={self.numbers}, strategy={self.strategy})>"
